require_relative './top_one_hundred_movies/version'
require_relative './top_one_hundred_movies/scraper'
require_relative './top_one_hundred_movies/movie'
require_relative './top_one_hundred_movies/cli'
require 'nokogiri'
require 'open-uri'
require 'actionview'
require 'activesupport'
require 'builder'
require 'erubi'
require 'rails-html-sanitizer'
require 'actionpack'
require 'activemodel'

